apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: Bohren-der-Club-of-Gore
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: Bohren-der-Club-of-Gore-band
subjects:
  - kind: ServiceAccount
    namespace: {{ .Values.namespace }}
    name: {{ .Values.name }}
